monolith_dbms/Models/Database.cs
using Microsoft.Data.Sqlite;
using System.Text.RegularExpressions;

namespace monolith_dbms.Models
{
	public interface IDatabase : IDisposable
	{
		public List<Table> Tables { get; }
		public ITableController TableController { get; }
		public string Name { get; }
		public bool CreateTable(Table table);
		public bool DropTable(Table table);
	}

	public class SqliteDatabase : IDatabase
	{
		private readonly SqliteConnection _connection;
		private readonly ITableController _tableController;
		private readonly List<Table> _tables;

		public List<Table> Tables => _tables;

		public ITableController TableController => _tableController;

		public string Name { get; private set; }

		public SqliteDatabase(string name)
		{
			_tables = [];
			_connection = new SqliteConnection($"Data Source={name}");
			_tableController = new SqliteTableController(_connection);
			_connection.Open();
			InitDatabase();
			Name = Path.GetFileName(name);
		}

		private void InitDatabase()
		{
			var getTablesCommand = _connection.CreateCommand();
			getTablesCommand.CommandText = "SELECT name FROM sqlite_master WHERE type='table';";

			using var tableReader = getTablesCommand.ExecuteReader();
			while (tableReader.Read())
			{
				string tableName = tableReader.GetString(0);
				var table = new Table(_tableController, tableName);

				var getColumnInfoCommand = _connection.CreateCommand();
				getColumnInfoCommand.CommandText = $"PRAGMA table_info({tableName});";

				using var columnReader = getColumnInfoCommand.ExecuteReader();
				while (columnReader.Read())
				{
					string columnName = columnReader.GetString(1);
					string columnType = columnReader.GetString(2);
					bool notNull = columnReader.GetBoolean(3);
					object? defaultValue = columnReader.IsDBNull(4) ? null : columnReader.GetValue(4);
					bool isPrimaryKey = columnReader.GetBoolean(5);

					var column = new Column(columnName, TypeManager.TypeMappings[columnType.ToUpper()](), notNull, defaultValue, isPrimaryKey);
					table.AddColumn(column);
				}
				AddTable(table);
			}
		}

		public bool CreateTable(Table table)
		{
			ValidateSqlIdentifier(table.Name);

			var (isValid, message) = table.ValidateColumns();
			if (!isValid) throw new DbmsException(message);

			var columns = table.Columns.Select((c) =>
			{
				ValidateSqlIdentifier(c.Name);
				var columnDef = $"{c.Name} {c.TypeName}";
				if (c.IsPk) columnDef += " PRIMARY KEY";
				if (c.IsNotNull) columnDef += " NOT NULL";
				if (c.DefaultValue != null) columnDef += $" DEFAULT {c.DefaultValue.ToString()}";

				return columnDef;
			});

			var command = _connection.CreateCommand();
			command.CommandText = $"CREATE TABLE {table.Name} ({string.Join(',', columns)});";

			command.ExecuteNonQuery();
			_tables.Add(table);
			return true;
		}

		public bool DropTable(Table table)
		{
			var command = _connection.CreateCommand();
			command.CommandText = $"DROP TABLE {table.Name}";
			command.ExecuteNonQuery();
			_tables.Remove(table);
			return true;
		}

		private void AddTable(Table table)
		{
			_tables.Add(table);
		}

		private void ValidateSqlIdentifier(string identifier)
		{
			if (string.IsNullOrWhiteSpace(identifier) || !Regex.IsMatch(identifier, @"^[a-zA-Z_][a-zA-Z0-9_]*$"))
			{
				throw new DbmsException($"Invalid SQL identifier: {identifier}");
			}
		}

		public void Dispose()
		{
			_connection.Dispose();
		}
	}
}

monolith_dbms/Models/ViewModels/DatabaseViewModel.cs
namespace monolith_dbms.Models.ViewModels
{
	public class DatabaseViewModel
	{
		public required string Id { get; set; }
		public required string Name { get; set; }
		public required List<Table> Tables { get; set; }
		public Table? SelectedTable { get; set; }
		public Column? SelectedColumn { get; set; }
		public string? SearchString { get; set; }
	}
}

monolith_dbms/Controllers/DatabaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OutputCaching;
using monolith_dbms.Models;
using monolith_dbms.Models.ViewModels;
using monolith_dbms.Services;
using System.Text.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace monolith_dbms.Controllers
{
	public class DatabaseController : Controller
	{
		private readonly IConnectionManager _connectionManager;
		private readonly ILogger<DatabaseController> _logger;

		public DatabaseController(IConnectionManager connectionManager, ILogger<DatabaseController> logger)
		{
			_connectionManager = connectionManager;
			_logger = logger;
		}

		[Route("Database/{id}")]
		public IActionResult Index(string id)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var model = new DatabaseViewModel
			{
				Id = id,
				Name = database.Name,
				Tables = database.Tables,
			};

			return View("Index", model);
		}

		[Route("Database/{id}/View/{tableName}")]
		public IActionResult Table(string id, string tableName, string? search)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var selectedTable = database.Tables.Find(t => t.Name == tableName);
			if (selectedTable == null) return NotFound();

			selectedTable.GetAllRows(search);

			var model = new DatabaseViewModel
			{
				Id = id,
				Name = database.Name,
				Tables = database.Tables,
				SelectedTable = selectedTable,
				SearchString = search,
			};

			return View("Index", model);
		}

		[Route("Database/{id}/View/{tableName}/{columnName}")]
		public IActionResult Column(string id, string tableName, string columnName)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var selectedTable = database.Tables.Find(t => t.Name == tableName);
			if (selectedTable == null) return NotFound();

			var selectedColumn = selectedTable.Columns.Find(c => c.Name == columnName);
			if (selectedColumn == null) return NotFound();

			var model = new DatabaseViewModel
			{
				Id = id,
				Name = database.Name,
				Tables = database.Tables,
				SelectedTable = selectedTable,
				SelectedColumn = selectedColumn,
			};

			return View("Index", model);
		}

		[HttpGet]
		[Route("Database/{id}/CreateRow/{tableName}")]
		public IActionResult CreateRow(string id, string tableName)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var selectedTable = database.Tables.Find(t => t.Name == tableName);
			if (selectedTable == null) return NotFound();

			var values = new Dictionary<string, string>();
			var columnNames = new Dictionary<string, string>();
			foreach (var col in selectedTable.Columns)
			{
				values.Add(col.Name, col.DefaultValue?.ToString() ?? "");
				string columnName = $"{col.Name} ({col.TypeName})";
				if (col.IsPk) columnName += " (pk)";
				if (col.IsNotNull) columnName += " (nn)";
				columnNames.Add(col.Name, columnName);
			}

			return View(new EditRowModel { Values = values, ColumnNames = columnNames });
		}

		[HttpPost]
		[Route("Database/{id}/CreateRow/{tableName}")]
		public IActionResult CreateRow(string id, string tableName, EditRowModel editRow)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var selectedTable = database.Tables.Find(t => t.Name == tableName);
			if (selectedTable == null) return NotFound();

			var columnValues = new ColumnValue[selectedTable.Columns.Count];
			foreach (var item in editRow.Values)
			{
				int index = selectedTable.Columns.FindIndex(c => c.Name == item.Key);
				if (index == -1)
				{
					ModelState.AddModelError($"Values[{item.Key}]", $"Error! {item.Key} column doesn't exists");
					break;
				}

				var c = selectedTable.Columns[index];
				columnValues[index] = c.Type.Instance(null, !c.IsNotNull);
				bool isValid = columnValues[index].ParseString(item.Value);
				if (!isValid) ModelState.AddModelError($"Values[{item.Key}]", $"Wrong value!");
			}

			if (!ModelState.IsValid)
			{
				return View(editRow);
			}

			try
			{
				bool isValid = selectedTable.AddRow(new Row(columnValues));
				if (!isValid) ModelState.AddModelError("", "Error!");
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("", ex.Message);
			}

			if (!ModelState.IsValid) return View(editRow);
			return RedirectToAction("Table", new { id, tableName });
		}

		[HttpGet]
		[Route("Database/{id}/EditRow/{tableName}/{pk}")]
		public IActionResult EditRow(string id, string tableName, string pk)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var selectedTable = database.Tables.Find(t => t.Name == tableName);
			if (selectedTable == null) return NotFound();

			int pkIndex = selectedTable.GetPkColumnIndex();
			if (pkIndex == -1 || string.IsNullOrEmpty(pk)) return NotFound();

			var pkValueObject = selectedTable.Columns[pkIndex].Type.Instance(pk, false);
			var row = selectedTable.Rows.Find(r => pkValueObject.ObjectValue?.Equals(r[pkIndex]?.ObjectValue) ?? false);
			if (row == null) return NotFound();

			var values = new Dictionary<string, string>();
			var columnNames = new Dictionary<string, string>();
			for (int i = 0; i < selectedTable.Columns.Count; i++)
			{
				var col = selectedTable.Columns[i];
				values.Add(col.Name, row[i].StringValue);
				string columnName = $"{col.Name} ({col.TypeName})";
				if (col.IsPk) columnName += " (pk)";
				if (col.IsNotNull) columnName += " (nn)";
				columnNames.Add(col.Name, columnName);
			}

			return View(new EditRowModel { Values = values, ColumnNames = columnNames });
		}

		[HttpPost]
		[Route("Database/{id}/EditRow/{tableName}/{pk}")]
		public IActionResult EditRow(string id, string tableName, string pk, EditRowModel editRow)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var selectedTable = database.Tables.Find(t => t.Name == tableName);
			if (selectedTable == null) return NotFound();

			int pkIndex = selectedTable.GetPkColumnIndex();
			if (pkIndex == -1 || string.IsNullOrEmpty(pk)) return NotFound();

			var pkValueObject = selectedTable.Columns[pkIndex].Type.Instance(pk, false);
			var rowIndex = selectedTable.Rows.FindIndex(r => pkValueObject.ObjectValue?.Equals(r[pkIndex]?.ObjectValue) ?? false);
			if (rowIndex == -1) return NotFound();

			bool onlyCheck = false;
			foreach (var item in editRow.Values)
			{
				int index = selectedTable.Columns.FindIndex(c => c.Name == item.Key);
				if (index == -1)
				{
					ModelState.AddModelError($"Values[{item.Key}]", $"Error! {item.Key} column doesn't exists");
					break;
				}

				try
				{
					bool isValid = selectedTable.ChangeCell(rowIndex, index, item.Value, onlyCheck);
					if (!isValid)
					{
						ModelState.AddModelError($"Values[{item.Key}]", $"Wrong value!");
						onlyCheck = true;
					}
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.Message);
				}

			}

			if (!ModelState.IsValid) return View(editRow);
			return RedirectToAction("Table", new { id, tableName });
		}

		[HttpGet]
		[Route("Database/{id}/CreateTable")]
		[OutputCache(NoStore = true, Duration = 0)]
		public IActionResult CreateTable(string id)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var data = new EditTableModel
			{
				Id = id,
				TableName = "",
				AvailableTypes = [.. TypeManager.AvailableTypes],
				Columns = [new ColumnDefinitionModel { TypeName = TypeManager.AvailableTypes[0] }]
			};

			return View(data);
		}

		[HttpPost]
		[Route("Database/{id}/CreateTable/AddColumn")]
		public IActionResult CreateTableAddColumn(string id, EditTableModel editTable)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var pkColumn = editTable.Columns[editTable.PrimaryKey ?? 0];
			editTable.Columns.RemoveAll(c => c.IsDeleted == true);

			int newPkIndex = editTable.Columns.IndexOf(pkColumn);
			editTable.PrimaryKey = newPkIndex == -1 ? 0 : newPkIndex;
			editTable.Columns = [.. editTable.Columns];

			editTable.Columns.Add(new ColumnDefinitionModel { TypeName = TypeManager.AvailableTypes[0] });
			editTable.AvailableTypes = [.. TypeManager.AvailableTypes];
			editTable.Id = id; ;

			return View("CreateTable", editTable);
		}

		[HttpPost]
		[Route("Database/{id}/CreateTable")]
		public IActionResult CreateTable(string id, EditTableModel editTable)
		{
			var database = _connectionManager.GetConnectionById(id);
			if (database == null) return NotFound();

			var pkColumn = editTable.Columns[editTable.PrimaryKey ?? 0];
			editTable.Columns.RemoveAll(c => c.IsDeleted == true);

			int newPkIndex = editTable.Columns.IndexOf(pkColumn);
			editTable.PrimaryKey = newPkIndex == -1 ? null : newPkIndex;
			editTable.Columns = [.. editTable.Columns];

			var table = new Table(database.TableController, editTable.TableName ?? "");
			for (int i = 0; i < editTable.Columns.Count; i++)
			{
				var c = editTable.Columns[i];

				if (string.IsNullOrWhiteSpace(c.TypeName))
					ModelState.AddModelError($"Columns[{i}].TypeName", "Invalid value");
				else if (!TypeManager.TypeMappings.ContainsKey(c.TypeName.ToUpper()))
					ModelState.AddModelError($"Columns[{i}].TypeName", "Type doesn't exists");

				if (!ModelState.IsValid) continue;

				if (string.IsNullOrWhiteSpace(c.Name))
					ModelState.AddModelError($"Columns[{i}].Name", "Invalid value");

				var typeObject = TypeManager.TypeMappings[c.TypeName!.ToUpper()]();
				var defaultValueObject = typeObject.Instance(null, false);
				bool isValid = defaultValueObject.ParseString(c.DefaultValue ?? "");

				if (!isValid && !string.IsNullOrEmpty(c.DefaultValue))

monolith_dbms/Views/Database/CreateRow.cshtml
@model EditRowModel

@{
	ViewData["Title"] = "Create a row";
}

@section Scripts
{
	<partial name="_ValidationScriptsPartial" />
}

<h3 class="mb-3">Create a new row</h3>
<form class="col-md-4" asp-action="CreateRow" method="post">
	@foreach(var value in Model.Values)
	{
		<div class="mb-3">
			@Html.HiddenFor(m => m.ColumnNames[value.Key])
			@Html.LabelFor(m => m.Values[value.Key], Model.ColumnNames[value.Key], new { @class = "form-label" })
			@Html.TextBoxFor(m => m.Values[value.Key], new { @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Values[value.Key])
		</div>		
	}
	@Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
	<button type="submit" class="btn btn-primary">Create</button>
</form>

monolith_dbms/Views/Database/CreateTable.cshtml
@model EditTableModel

@{
	ViewData["Title"] = "Create a table";
}

<h3 class="mb-3">Create a new table</h3>
<form id="createTableForm" class="col-md-4" method="post">
	<div class="mb-3">
		@Html.LabelFor(m => m.TableName, "Table Name", new { @class = "form-label" })
		@Html.TextBoxFor(m => m.TableName, new { @class = "form-control form-control-lg" })
		@Html.ValidationMessageFor(m => m.TableName)
	</div>
	@for (int i = 0; i < Model.Columns.Count; i++)
	{
		<div class="p-4 my-3 border rounded">
			<div class="mb-3">
				@Html.LabelFor(m => m.Columns[i].Name, "Column Name", new { @class = "form-label" })
				@Html.TextBoxFor(m => m.Columns[i].Name, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Columns[i].Name)
			</div>
			<div class="mb-3">
				@Html.LabelFor(m => m.Columns[i].TypeName, "Type", new { @class = "form-label" })
				@Html.DropDownListFor(m => m.Columns[i].TypeName, new SelectList(Model.AvailableTypes), new { @class = "form-select" })
				@Html.ValidationMessageFor(m => m.Columns[i].TypeName)
			</div>
			<div class="mb-3">
				@Html.LabelFor(m => m.Columns[i].DefaultValue, "Default Value", new { @class = "form-label" })
				@Html.TextBoxFor(m => m.Columns[i].DefaultValue, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Columns[i].DefaultValue)
			</div>
			<div class="mb-3">
				@Html.RadioButtonFor(m => m.PrimaryKey, i, new { @class = "form-check-input", id = $"PrimaryKey[{i}]" }) 
				@Html.LabelFor(m => m.PrimaryKey, "Primary key", new { @class = "form-check-label", @for = $"PrimaryKey[{i}]" })
				@Html.ValidationMessageFor(m => m.PrimaryKey)
			</div>
			<div class="form-check mb-3">
				@Html.CheckBoxFor(m => m.Columns[i].IsNotNull, new { @class = "form-check-input" })
				@Html.LabelFor(m => m.Columns[i].IsNotNull, "Not null", new { @class = "form-check-label" })
				@Html.ValidationMessageFor(m => m.Columns[i].IsNotNull)
			</div>
			@Html.HiddenFor(m => m.Columns[i].IsDeleted)
			<button type="button" class="btn btn-outline-danger" onclick="@($"deleteColumn(\"Columns_{i}__IsDeleted\")")">Remove</button>
		</div>
	}
	<button id="addColumnBtn" type="submit" class="btn btn-outline-primary mb-3">Add column</button>
	@Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
	<button id="createTableBtn" type="submit" class="btn btn-primary w-100 btn-lg">Create</button>
</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />

    <script>
		document.getElementById('createTableBtn').onclick = function(e) {
			const form = document.getElementById('createTableForm');
			form.action = '@Url.Action("CreateTable", new { id = Model.Id })';
        };

		document.getElementById('addColumnBtn').onclick = function(e) {
			const form = document.getElementById('createTableForm');
			form.action = '@Url.Action("CreateTableAddColumn", new { id = Model.Id })';
        };

		function deleteColumn(id) {
			const input = document.getElementById(id);
			input.value = true;
			input.parentElement.classList.add('d-none');
		}
    </script>
}

monolith_dbms/Views/Database/EditRow.cshtml
@model EditRowModel

@{
	ViewData["Title"] = "Edit a row";
}

@section Scripts
{
		<partial name="_ValidationScriptsPartial" />
}

<h3 class="mb-3">Create a new row</h3>
<form class="col-md-4" asp-action="EditRow" method="post">
	@foreach (var value in Model.Values)
	{
			<div class="mb-3">
				@Html.HiddenFor(m => m.ColumnNames[value.Key])
				@Html.LabelFor(m => m.Values[value.Key], Model.ColumnNames[value.Key], new { @class = "form-label" })
				@Html.TextBoxFor(m => m.Values[value.Key], new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Values[value.Key])
			</div>		
	}
	@Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
	<button type="submit" class="btn btn-primary">Edit</button>
</form>

monolith_dbms/Views/Database/Index.cshtml
@model DatabaseViewModel

@{
    ViewData["Title"] = Model.Name;
    if (Model.SelectedTable != null) ViewData["Title"] += $".{Model.SelectedTable.Name}";
    ViewData["Title"] += " - DBMS";
}

<div class="row">
    <div class="col-md-2">
        @await Html.PartialAsync("_TreeView", Model)
    </div>
    <div class="col-md-10">
        @if (Model.SelectedColumn != null)
        {
            @await Html.PartialAsync("_ColumnPanel", Model)
        }
        else if (Model.SelectedTable != null)
        {
            @await Html.PartialAsync("_TablePanel", Model)
        }
        else
        {
            <div></div>
        }
    </div>
</div>

monolith_dbms/Views/Database/_ColumnPanel.cshtml
@model DatabaseViewModel

@{
	var column = Model.SelectedColumn;
	if (column == null) return;
}

<table class="table table-borderless table-sm w-25">
	<tbody>
		<tr>
			<td>Name:</td>
			<td>@column.Name</td>
		</tr>
		<tr>
			<td>Type:</td>
			<td>@column.TypeName</td>
		</tr>
		<tr>
			<td>Primary key (pk):</td>
			<td>@column.IsPk</td>
		</tr>
		<tr>
			<td>Not null (nn):</td>
			<td>@column.IsNotNull</td>
		</tr>
		<tr>
			<td>Default value:</td>
			<td>@(column.DefaultValue ?? "")</td>
		</tr>
	</tbody>
</table>

monolith_dbms/Views/Database/_TablePanel.cshtml
@model DatabaseViewModel

@{
	var table = Model.SelectedTable;
	if (table == null) return;
}

@functions {
    public string GetColumnName(Column column)
    {
        string result = column.Name;
        if (column.IsPk) result += " (pk)";
        if (column.IsNotNull) result += " (nn)";
        return result;
    }

    public string? GetPkValue(Row row)
    {
        return row[Model.SelectedTable!.GetPkColumnIndex()].ObjectValue?.ToString();
    }
}

<div class="hstack gap-3 mb-3">
    <a href="@Url.Action("CreateRow", new { id = Model.Id, tableName = table.Name })" class="btn btn-success flex-shrink-0">Add Row</a>
    <button 
        type="button" 
        class="btn btn-danger" 
        data-bs-toggle="modal" 
        data-bs-target="#dropTableModal"
        onclick="setDeletePath(this)"
    >
        Drop Table
    </button>
    <div class="vr"></div>
    <form class="me-auto d-flex flex-grow-1 gap-3" method="get" action="@Url.Action("Table", new { id = Model.Id, tableName = table.Name })">
        <input type="search" name="search" class="form-control" placeholder="Search..." value="@Model.SearchString">
        <button type="submit" class="btn btn-outline-secondary flex-shrink-0">Search</button>
    </form>
</div>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
        @foreach(var col in table.Columns)
        {
            <th scope="col">@GetColumnName(col)</th>
        }
        <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
        @foreach(var row in table.Rows)
        {
            <tr>
                @foreach(var item in row)
                {
                    <td>@item.StringValue</td>
                }
                <td>
                    <a href="@Url.Action("EditRow", new { id = Model.Id, tableName = table.Name, pk = GetPkValue(row) })" class="btn btn-outline-primary">Edit</a>
                    <button 
                        type="button" 
                        class="btn btn-danger" 
                        data-bs-toggle="modal" 
                        data-bs-target="#deleteRowModal"
                        data-pk-value="@GetPkValue(row)"
                        onclick="setDeleteRow(this)"
                    >
                        Delete
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="dropTableModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="Drop table modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Warning!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to drop "@table.Name". This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form asp-action="DropTable" method="post" style="display:inline;">
            <input type="hidden" name="id" value="@Model.Id" />
            <input type="hidden" name="tableName" value="@table.Name" />
            <button type="submit" class="btn btn-danger">Drop</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="deleteRowModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="Delete row modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Warning!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this row. This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form asp-action="DeleteRow" method="post" style="display:inline;">
            <input type="hidden" name="id" value="@Model.Id" />
            <input type="hidden" name="tableName" value="@table.Name" />
            <input type="hidden" id="deleteRowValue" name="pkValue" value="" />
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>


<script>
   function setDeleteRow(button) {
       const value = button.getAttribute('data-pk-value');
       document.getElementById('deleteRowValue').value = value;
   }
</script>

monolith_dbms/Views/Database/_TreeView.cshtml
@model DatabaseViewModel

@if (Model.Tables.Count == 0)
{
	<div class="d-flex justify-content-start align-items-center">
		<h3>Nothing here</h3>
	</div>
	return;
}

<div class="pe-4 border-end pb-3">
    <a href="@Url.Action("CreateTable", new { id = Model.Id })" class="btn btn-outline-primary">Create Table</a>
</div>
<nav class="h-100 flex-column align-items-stretch pe-4 border-end">
    @foreach (var table in Model.Tables)
    {
        <nav class="nav nav-pills flex-column">
            <a class="@($"nav-link {(table == Model.SelectedTable ? "active" : "")}")" href="@Url.Action("Table", "Database", new { id = Model.Id, tableName = table.Name })">
                @table.Name
            </a>
            <nav class="nav nav-pills flex-column">
                @foreach (var column in table.Columns)
                {
                    <a 
                        class="@($"nav-link ms-3 my-1 {(table == Model.SelectedTable && column == Model.SelectedColumn ? "active" : "")}")" 
                        href="@Url.Action("Column", "Database", new { id = Model.Id, tableName = table.Name, columnName = column.Name })"
                    >
                        @column.Name
                    </a>
                }
            </nav>
        </nav>
    }
</nav>